name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  # Github token permissions to write to the repo
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Transform the tokens
        run: npm run token-transformer
      - name: Build styles
        run: npm run style-dictionary
      # Commit all changed files back to the repository
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@e8f94e4dd298db5a6a2aa2d42fe0bcef6f2c9660
        with:
          commit_message: "Action: Build style-dictionary from tokens"
